W6D5/99 cats/cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

W6D5/99 cats/cats/app/models/cat.rb
require "action_view"
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  COLORS = ['orange', 'black', 'white', 'gray']
  SEXES = ['M', 'F']
  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: {in: COLORS}
  validates :sex, inclusion: {in: SEXES}

  def age
    time_ago_in_words(birth_date)
  end
end

W6D5/99 cats/cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    @colors = ['orange', 'black', 'white', 'gray']
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat.id)
    else
      render :new
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

W6D5/99 cats/cats/app/views/cats/index.html.erb
<h1>These are all the cats</h1>
<h1>These are available cats</h1>
<table>
  <tr>
    <th>Birthday</th>
    <th>Color</th>
    <th>Name</th>
    <th>Sex</th>
  </tr>
  <tr>
  <%@cats.each do |cat|%>
    <td><%= cat.birth_date %></td>
    <td><%= cat.color %></td>
    <td><%= cat.name %></td>
    <td><%= cat.sex %></td>
    <% end %>
  </tr>
</table>

W6D5/99 cats/cats/app/views/cats/new.html.erb
<h1>Create a new cat!</h1>

<form action="<%=cats_url%>" method="POST">
  <label>Name:
  <input type="text" name="cat[name]" value="<%=@cat.name%>">
  </label>
  <br>
  <label>Sex:
  <label>Male</label>
  <input type="radio" name="cat[sex]" value=<%=@cat.sex = 'M'%>>
  <label>Female</label>
  <input type="radio" name="cat[sex]" value=<%=@cat.sex = 'F'%>>
  </label>
  <br>
  <label>Birthdate:</label>
  <input type="date" name="cat[birth_date]" value="<%=@cat.name%>">
  <br>
  <label>Description:</label>
  <textarea name="cat[description]"><%=@cat.description%></textarea>
  <br>
  <label>Color:
  <select name="cat[color]">
  <label>Black<option name="cat[color]" value=<%@cat.color='black'%>></label>
    <label>Black<option name="cat[color]" value=<%@cat.color='black'%>></label>
    <label>White<option name="cat[color]" value=<%@cat.color='white'%>></label>
    <label>Gray<option name="cat[color]" value=<%@cat.color='gray'%>></label>
    <label>Orange<option name="cat[color]" value=<%@cat.color='orange'%>></label>
  </select>
  </label>
 
  <input type="submit" value="Create Cat">
</form>

W6D5/99 cats/cats/app/views/cats/show.html.erb
<h1>These are available cats</h1>
<table>
  <tr>
    <th>Birthday</th>
    <th>Color</th>
    <th>Name</th>
    <th>Sex</th>
  </tr>
  <tr>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.name %></td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

W6D5/99 cats/cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

W6D5/99 cats/cats/app/views/layouts/show.html.erb
<h1>These are available cats</h1>
<table>
  <tr>
    <th>Birthday</th>
    <th>Color</th>
    <th>Name</th>
    <th>Sex</th>
  </tr>
  <tr>
    <td><%= @cats.birth_date %></td>
    <td><%= @cats.color %></td>
    <td><%= @cats.name %></td>
    <td><%= @cats.sex %></td>
  </tr>
</table>